name: Build & Deploy to VPS with GHCR

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/polysim/documentation-back:latest -f apps/documentation-back/Dockerfile .

      - name: Push image
        run: docker push ghcr.io/polysim/documentation-back:latest

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker login ghcr.io -u "${{ secrets.REGISTRY_USER }}" -p "${{ secrets.REGISTRY_TOKEN }}"
            docker pull ghcr.io/polysim/documentation-back:latest
            docker stop documentation-back || true
            docker rm documentation-back || true
            docker run -d --name documentation-back -p 5067:5067 -v /usr/src/app/Documentation:/usr/src/app/Documentation ghcr.io/polysim/documentation-back:latest
